version: '3.7'
services: 
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5901:5900
  website:
    build: 
      context: .
      # name: website
    ports:
    - 8000:8000
  # database:
  # aplication_server:
  unit-tests:
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    build:
      context: .
      dockerfile: rspec.Dockerfile
    volumes:
      - .:/app # ${PWD}/:/var/www/html
    command: 
      - --pattern
      - /app/spec/unit/*_spec.rb
