version: '3.7'
services: 
  website:
    build: 
      context: .
      # name: website
    ports:
    - 8000:8000 
  # database:
  # aplication_server:
  unit-tests:
    build:
      context: .
      dockerfile: rspec.Dockerfile
    volumes:
      - .:/app # ${PWD}/:/var/www/html
    command: 
      - --pattern
      - /app/spec/unit/*_spec.rb
